/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'PascalMacBookPro' at '2/10/17 3:36 PM' with Gradle 2.14.1
 *
 * @author PascalMacBookPro, @date 2/10/17 3:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
